'use strict';
// Bounded source harness. No engine edits, transport, sit API, player scaling, or map/camera expansion.
const desks=[{id:'left',x:160,y:128,width:64,height:64,cx:192},{id:'right',x:256,y:128,width:64,height:64,cx:288}];
const scope='Actual Phaser 3.86 Arcade source harness, not full Universe. One moving unchanged Greg and one stationary unchanged scale fixture. No multiplayer or claimability assertion.';
const report={scope,assertions:[],checkpoints:[],collisions:[],samples:[],errors:[],fixtureRepositions:[]};
let scene,game,running=false,motion=null,phase='ready',lastSample=0;
const show=(s)=>document.querySelector('#status').textContent=s;
window.addEventListener('error',e=>report.errors.push(e.message));
window.addEventListener('unhandledrejection',e=>report.errors.push(String(e.reason)));
const assert=(name,pass,detail)=>{report.assertions.push({name,pass,detail});if(!pass)throw Error(name+': '+JSON.stringify(detail));};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const rendered=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
const fixed={dt:1/60,speed:96};
function snapshot(){const p=scene.player,b=p.body;return {phase,player:{x:p.x,y:p.y,frame:scene.greg.frame.name,width:scene.greg.width,height:scene.greg.height,scaleX:scene.greg.scaleX,scaleY:scene.greg.scaleY},body:{x:b.x,y:b.y,width:b.width,height:b.height,vx:b.velocity.x,vy:b.velocity.y,blocked:{...b.blocked}},fixture:{x:scene.fixture.x,y:scene.fixture.y,frame:scene.fixture.frame.name,width:scene.fixture.width,height:scene.fixture.height,scaleX:scene.fixture.scaleX,scaleY:scene.fixture.scaleY},deskFootprints:desks.map(d=>({id:d.id,x:d.x,y:d.y,width:d.width,height:d.height})),layers:{baseDepth:0,playerDepth:p.depth,fixtureDepth:scene.fixture.depth,backDepth:scene.backs.depth,backPosition:[scene.backs.x,scene.backs.y]},renderer:{version:Phaser.VERSION,type:game.renderer.type===Phaser.CANVAS?'CANVAS':'WEBGL',width:game.canvas.width,height:game.canvas.height,pixelArt:game.config.pixelArt,antialias:game.config.antialias,cameraZoom:scene.cameras.main.zoom},visibility:document.visibilityState};}
function walkTo(x,y,label){phase=label;show(label);return new Promise((resolve,reject)=>{motion={kind:'target',x,y,resolve,reject,started:performance.now()};});}
function pushNorth(ms,label){phase=label;show(label);return new Promise((resolve,reject)=>{motion={kind:'north',until:performance.now()+ms,resolve,reject,started:performance.now()};});}
function stop(){scene.player.body.setVelocity(0,0);scene.greg.setFrame(scene.facing*3+1);}
function moveFixture(x){scene.fixture.setPosition(x,192).setFrame(10);report.fixtureRepositions.push({phase,x,y:192,reason:'Stationary scale fixture changes seats between independent left/right test cases; not a second live player.'});}
function intersect(a,d){return a.x<d.x+d.width-0.001&&a.x+a.width>d.x+0.001&&a.y<d.y+d.height-0.001&&a.y+a.height>d.y+0.001;}
async function save(name,kind,value){const response=await fetch('/qa/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,[kind]:value})});if(!response.ok)throw Error('Save failed '+name+': '+response.status);return response.json();}
async function capture(name){await rendered();const c=game.canvas;await save(name+'-native-1x','png',c.toDataURL('image/png'));for(const crop of [{suffix:'native-2x',x:0,y:0,w:512,h:384,scale:2},{suffix:'tight-1x',x:128,y:112,w:240,h:160,scale:1},{suffix:'tight-2x',x:128,y:112,w:240,h:160,scale:2}]){const out=document.createElement('canvas');out.width=crop.w*crop.scale;out.height=crop.h*crop.scale;const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(c,crop.x,crop.y,crop.w,crop.h,0,0,out.width,out.height);await save(name+'-'+crop.suffix,'png',out.toDataURL('image/png'));}const s=snapshot();report.checkpoints.push({name,...s});await save(name+'-state','report',s);}
function record(){const stream=game.canvas.captureStream(30),chunks=[];const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:1500000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start();return async()=>{await new Promise(r=>{recorder.onstop=r;recorder.stop();});stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'video/webm'});const data=await new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.readAsDataURL(blob);});await save('physical-entry-exit-motion','webm',data);return {bytes:blob.size,type:blob.type};};}
async function seatTest(x,id){await walkTo(x,272,'Approach '+id+' seat along rear aisle');await pushNorth(1650,'Walk north into '+id+' desk collider');stop();await rendered();const s=snapshot();assert(id+' exact desk stop',Math.abs(s.player.x-x)<0.001&&Math.abs(s.player.y-192)<0.001,s.player);assert(id+' native body',Math.abs(s.body.x-(x-8))<.001&&Math.abs(s.body.y-192)<.001&&s.body.width===16&&s.body.height===16,s.body);assert(id+' north idle',Number(s.player.frame)===10,s.player);await capture('occupied-'+id);await sleep(550);await walkTo(x,272,'Exit '+id+' seat physically into rear aisle');assert(id+' exit',Math.abs(scene.player.y-272)<0.001,snapshot().player);}
async function runProof(){if(running)return;running=true;document.querySelector('#verify').disabled=true;let finish;try{assert('initial position',Math.abs(scene.player.x-128)<0.001&&Math.abs(scene.player.y-272)<0.001,snapshot().player);assert('Phaser version',Phaser.VERSION==='3.86.0',Phaser.VERSION);assert('native canvas and camera',game.canvas.width===512&&game.canvas.height===384&&scene.cameras.main.zoom===1,snapshot().renderer);finish=record();await seatTest(192,'left');await walkTo(352,272,'Rear aisle eastbound');moveFixture(192);await seatTest(288,'right');await walkTo(352,272,'East side bypass approach');await walkTo(128,272,'Traverse 64 px rear aisle westbound');await capture('rear-aisle');await walkTo(128,96,'Traverse west side bypass northbound');await walkTo(352,96,'Traverse north bypass eastbound');await walkTo(352,272,'Traverse east side bypass southbound');await capture('side-bypass-return');await walkTo(288,272,'Return to right seat approach');await pushNorth(1650,'Final physical right-seat contact');stop();await capture('final-occupied');report.video=await finish();finish=null;assert('no desk overlap during all recorded steps',report.samples.every(s=>!s.deskOverlap),{samples:report.samples.length});assert('fixed genuine back mask throughout',report.samples.every(s=>s.backX===0&&s.backY===0&&s.backDepth===1000),{samples:report.samples.length});assert('native Greg size throughout',report.samples.every(s=>s.spriteWidth===32&&s.spriteHeight===32&&s.scaleX===1&&s.scaleY===1),{samples:report.samples.length});assert('no runtime errors',report.errors.length===0,report.errors);report.completed=true;report.finishedAt=new Date().toISOString();report.limitation='Both seats shown occupied when the moving player is at a desk. Aisle routes use one stationary occupant and one moving player; no third avatar or live multiplayer collision is claimed.';await save('runtime-verification','report',report);show('PASS: both seats entered and exited; exact y192 collider stops; rear aisle and side bypasses clear. Native captures and motion saved.');}catch(e){report.completed=false;report.errors.push(String(e));if(motion){motion=null;stop();}if(finish)try{report.video=await finish();}catch(err){report.errors.push(String(err));}await save('runtime-verification','report',report);show('FAIL: '+e.message);}finally{running=false;document.querySelector('#state').textContent=JSON.stringify({summary:report.assertions,final:snapshot(),errors:report.errors},null,2);}}
class NativeFixtureScene extends Phaser.Scene{
 preload(){this.load.spritesheet('greg','assets/greg.png',{frameWidth:32,frameHeight:32});this.load.image('station','assets/single-station-native.png');this.load.image('backs','assets/fixture-chair-backs-native.png');}
 create(){scene=this;this.cameras.main.setBackgroundColor('#e4ddc7').setZoom(1).setRoundPixels(true);this.physics.world.setBounds(0,0,512,384);for(const d of desks)this.add.image(d.x-16,d.y-16,'station').setOrigin(0).setDepth(0);const collisionTexture=this.textures.createCanvas('collision-cell',32,32);collisionTexture.context.fillRect(0,0,32,32);collisionTexture.refresh();const collisionMap=this.make.tilemap({tileWidth:32,tileHeight:32,width:16,height:12});const collisionTiles=collisionMap.addTilesetImage('collision-cell','collision-cell',32,32);this.deskLayer=collisionMap.createBlankLayer('exact-desk-collisions',collisionTiles,0,0).setVisible(false);for(const d of desks)for(let y=d.y/32;y<(d.y+d.height)/32;y++)for(let x=d.x/32;x<(d.x+d.width)/32;x++)this.deskLayer.putTileAt(0,x,y);this.deskLayer.setCollision(0);
 this.player=this.add.container(128,272);this.greg=this.add.sprite(0,0,'greg',1);this.player.add(this.greg);this.player.getBody=()=>this.player.body;fork.configureBody.call(this.player);this.fixture=this.add.sprite(288,192,'greg',10).setDepth(208);this.backs=this.add.image(0,0,'backs').setOrigin(0).setDepth(1000);this.facing=0;this.physics.add.collider(this.player,this.deskLayer,(_,tile)=>{if(report.collisions.length<500)report.collisions.push({tileX:tile.x,tileY:tile.y,bodyX:this.player.body.x,bodyY:this.player.body.y,phase});});this.keys=this.input.keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT');document.querySelector('#verify').disabled=false;document.querySelector('#capture').disabled=false;document.querySelector('#verify').onclick=runProof;document.querySelector('#capture').onclick=()=>capture('manual-current');show('Ready: physical walk begins at (128,272). Right seat holds one stationary scale fixture.');}
 update(time){if(!this.player)return;const p=this.player,b=p.body;let vx=0,vy=0;if(motion){if(document.visibilityState!=='visible'){const m=motion;motion=null;stop();m.reject(Error('QA tab lost foreground'));return;}if(performance.now()-motion.started>12000){const m=motion;motion=null;stop();m.reject(Error('Movement timed out: '+phase));return;}if(motion.kind==='north'){if(performance.now()>=motion.until){const m=motion;motion=null;stop();m.resolve();}else vy=-fixed.speed;}else{const dx=motion.x-(b.x+8),dy=motion.y-b.y;if(Math.abs(dx)<.001&&Math.abs(dy)<.001){const m=motion;motion=null;stop();m.resolve();}else if(Math.abs(dx)>.001)vx=Math.sign(dx)*Math.min(fixed.speed,Math.abs(dx)/fixed.dt);else vy=Math.sign(dy)*Math.min(fixed.speed,Math.abs(dy)/fixed.dt);}}else if(!running){vx=(this.keys.RIGHT.isDown||this.keys.D.isDown?1:0)-(this.keys.LEFT.isDown||this.keys.A.isDown?1:0);vy=(this.keys.DOWN.isDown||this.keys.S.isDown?1:0)-(this.keys.UP.isDown||this.keys.W.isDown?1:0);if(vx&&vy){vx/=Math.SQRT2;vy/=Math.SQRT2;}vx*=fixed.speed;vy*=fixed.speed;}
 b.setVelocity(vx,vy);if(vy<0)this.facing=3;else if(vy>0)this.facing=0;else if(vx<0)this.facing=1;else if(vx>0)this.facing=2;const deskStop=desks.some(d=>p.x>=d.x+8&&p.x<=d.x+d.width-8&&Math.abs(p.y-192)<.001&&vy<=0&&vx===0);if(deskStop)this.facing=3;const moving=Math.hypot(b.deltaX(),b.deltaY())>.01;this.greg.setFrame(this.facing*3+(moving?Math.floor(time/130)%3:1));p.setDepth(fork.characterDepth.call(p));if(running&&time-lastSample>=30){lastSample=time;report.samples.push({time,phase,x:b.x+8,y:b.y,bodyX:b.x,bodyY:b.y,deskOverlap:desks.some(d=>intersect(b,d)),backX:this.backs.x,backY:this.backs.y,backDepth:this.backs.depth,spriteWidth:this.greg.width,spriteHeight:this.greg.height,scaleX:this.greg.scaleX,scaleY:this.greg.scaleY});}if(!running)document.querySelector('#state').textContent=JSON.stringify(snapshot(),null,2);}
}
game=new Phaser.Game({type:Phaser.CANVAS,parent:'game',width:512,height:384,backgroundColor:'#e4ddc7',pixelArt:true,antialias:false,roundPixels:true,physics:{default:'arcade',arcade:{gravity:{x:0,y:0},fps:60,fixedStep:true,debug:false}},scene:NativeFixtureScene});
