'use strict';
let scene,game,motion=null,running=false,proof={};const status=t=>document.querySelector('#status').textContent=t;
const intersect=(a,b)=>a.x<b.x+b.width-.001&&a.x+a.width>b.x+.001&&a.y<b.y+b.height-.001&&a.y+a.height>b.y+.001;
const state=()=>({position:[scene.player.x,scene.player.y],body:{x:scene.player.body.x,y:scene.player.body.y,width:scene.player.body.width,height:scene.player.body.height},frame:scene.sprite.frame.name,scale:[scene.sprite.scaleX,scene.sprite.scaleY],nativeCanvas:[game.canvas.width,game.canvas.height],cameraZoom:scene.cameras.main.zoom});
function setStart(x,y){scene.player.body.reset(x,y);scene.player.setPosition(x,y);scene.player.body.setVelocity(0);scene.sprite.setFrame(1);}
function walk(x,y){return new Promise((resolve,reject)=>motion={x,y,resolve,reject,start:performance.now()});}
async function run(){if(running)return;running=true;proof={scope:'Phaser 3.86 Arcade source harness; one moving native Greg; other characters are stationary scale fixtures. Exact rectangle collisions, not a deployed Universe map.',checks:[],samples:[],errors:[],startedAt:new Date().toISOString()};let errors=[];try{for(const route of civic.m.routes){scene.hideFixture(route.target);setStart(...route.points[0]);for(const point of route.points.slice(1))await walk(...point);const final=state();if(Math.abs(final.position[0]-route.points.at(-1)[0])>.1||Math.abs(final.position[1]-route.points.at(-1)[1])>.1)throw Error('wrong endpoint');proof.checks.push({route:route.id,forward:true,state:final});if(['speaker-via-right-stairs','enter-student-1','enter-attendee-1'].includes(route.id)){scene.sprite.setFrame(route.target==='speaker'?1:10);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));await civic.save('physical-'+route.id,'png',game.canvas.toDataURL());}for(const point of route.points.slice(0,-1).reverse())await walk(...point);proof.checks.push({route:route.id,reverse:true,state:state()});scene.showFixtures();status('Verified '+route.id);}proof.passed=proof.samples.every(s=>!s.overlap)&&proof.errors.length===0;proof.finishedAt=new Date().toISOString();await civic.save('physical-route-report','report',proof);status('PASS: '+proof.checks.length+' forward/reverse routes physically walked. Native static occupied proof also exported.');}catch(e){proof.passed=false;proof.errors.push(String(e));await civic.save('physical-route-report','report',proof);status('FAIL '+e.message);}finally{running=false;scene.showFixtures();}}
class CivicScene extends Phaser.Scene{
 preload(){this.load.spritesheet('greg','../assets/greg.png',{frameWidth:32,frameHeight:32});}
 create(){scene=this;this.physics.world.setBounds(0,0,640,1152);for(const [name,c]of Object.entries(civic.layers)){this.textures.addCanvas(name,c);this.add.image(0,0,name).setOrigin(0).setDepth(name==='architecture'?0:name==='furniture'?1:10000+(name==='foreground'?0:name==='glass'?1:2));}this.fixtures=[];for(const a of [...civic.m.students,...civic.m.audience,civic.m.teacher,civic.m.speaker]){let f=this.add.sprite(...a.center,'greg',a.frame).setDepth(a.center[1]+16);this.fixtures.push({id:a.id,f});}this.hideFixture=id=>this.fixtures.forEach(o=>o.f.setVisible(o.id!==id));this.showFixtures=()=>this.fixtures.forEach(o=>o.f.setVisible(true));this.player=this.add.container(624,992);this.sprite=this.add.sprite(0,0,'greg',1);this.player.add(this.sprite);this.player.getBody=()=>this.player.body;fork.configureBody.call(this.player);this.solids=[];for(const r of civic.m.blockers){const s=this.add.rectangle(r.x+r.width/2,r.y+r.height/2,r.width,r.height,0xff0000,0);this.physics.add.existing(s,true);this.physics.add.collider(this.player,s);this.solids.push(s);}this.keys=this.input.keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT');document.querySelector('#classroom').onclick=()=>{if(!running)setStart(624,384)};document.querySelector('#hall').onclick=()=>{if(!running)setStart(624,992)};document.querySelector('#capture').onclick=civic.export;document.querySelector('#test').onclick=run;window.runCivicProof=run;window.civicReady=true;status('Ready. Use arrows/WASD or run the bounded proof.');}
 update(t){if(!this.player)return;let vx=0,vy=0;const b=this.player.body;if(motion){if(performance.now()-motion.start>5000){const m=motion;motion=null;m.reject(Error('Timeout route at '+b.x+','+b.y+' to '+m.x+','+m.y));return;}const dx=motion.x-(b.x+8),dy=motion.y-b.y;if(Math.abs(dx)<.02&&Math.abs(dy)<.02){const m=motion;motion=null;b.setVelocity(0);m.resolve();}else if(Math.abs(dx)>.02)vx=Math.sign(dx)*Math.min(720,Math.abs(dx)*60);else vy=Math.sign(dy)*Math.min(720,Math.abs(dy)*60);}else if(!running){vx=((this.keys.RIGHT.isDown||this.keys.D.isDown)?1:0)-((this.keys.LEFT.isDown||this.keys.A.isDown)?1:0);vy=((this.keys.DOWN.isDown||this.keys.S.isDown)?1:0)-((this.keys.UP.isDown||this.keys.W.isDown)?1:0);if(vx&&vy){vx/=Math.SQRT2;vy/=Math.SQRT2;}vx*=112;vy*=112;}b.setVelocity(vx,vy);if(vx||vy){this.facing=vy<0?3:vy>0?0:vx<0?1:2;this.sprite.setFrame(this.facing*3+Math.floor(t/140)%3);}else this.sprite.setFrame((this.facing||0)*3+1);this.player.setDepth(fork.characterDepth.call(this.player));if(running)proof.samples.push({x:b.x+8,y:b.y,overlap:civic.m.blockers.some(r=>intersect(b,r)),spriteScale:this.sprite.scaleX,body:[b.width,b.height]});document.querySelector('#state').textContent=JSON.stringify(state(),null,2);}
}
(async()=>{await civic.init();game=new Phaser.Game({type:Phaser.CANVAS,parent:'game',width:640,height:1152,backgroundColor:'#14282a',pixelArt:true,antialias:false,roundPixels:true,physics:{default:'arcade',arcade:{gravity:{x:0,y:0},fps:60,fixedStep:true}},scene:CivicScene});})();
