'use strict';
/* Native source harness: exact TMJ collisions, unchanged Woka body and source depth primitive. */
const scope='Phaser 3.86 source harness. One moving unchanged Greg. No live Universe, multiplayer, claims, bot or conference-service assertion.';
// 120px/s is exactly2px per60Hz physics step, avoiding cumulative1.6px rounding
// on author-approved zero-clearance sofa routes. No body/engine/collision change.
const settings={speed:120,dt:1/60,width:1024,height:704};
let scene,game,motion=null,running=false,phase='ready',lastSample=0,report;
const show=text=>document.querySelector('#status').textContent=text;
const rendered=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function freshReport(mode){return {scope,mode,startedAt:new Date().toISOString(),assertions:[],checkpoints:[],collisions:[],samples:[],errors:[],completed:false};}
report=freshReport('manual');
window.addEventListener('error',event=>report.errors.push(event.message));
window.addEventListener('unhandledrejection',event=>report.errors.push(String(event.reason)));
function assert(name,pass,detail){report.assertions.push({name,pass,detail});if(!pass)throw Error(name+': '+JSON.stringify(detail));}
function snapshot(){const p=scene.player,b=p.body,c=scene.cameras.main;return {phase,player:{x:p.x,y:p.y,frame:Number(scene.greg.frame.name),width:scene.greg.width,height:scene.greg.height,scaleX:scene.greg.scaleX,scaleY:scene.greg.scaleY,depth:p.depth},body:{x:b.x,y:b.y,width:b.width,height:b.height,immovable:b.immovable,vx:b.velocity.x,vy:b.velocity.y,blocked:{...b.blocked}},camera:{scrollX:c.scrollX,scrollY:c.scrollY,zoom:c.zoom,width:c.width,height:c.height},renderer:{version:Phaser.VERSION,type:game.renderer.type===Phaser.CANVAS?'CANVAS':'WEBGL',width:game.canvas.width,height:game.canvas.height,pixelArt:game.config.pixelArt,antialias:game.config.antialias},collision:{kind:'Phaser.Tilemaps.TilemapLayer',cellSize:scene.map.tileWidth,tileCount:scene.collisionCells.size,opacity:scene.collisionLayer.alpha,visible:scene.collisionLayer.visible},layers:scene.phaserLayers.map(l=>({name:l.layer.name,depth:l.depth,x:l.x,y:l.y,alpha:l.alpha})),compileStatus:scene.compile.status,visibility:document.visibilityState};}
function bodyOverlap(){const b=scene.player.body,epsilon=.0001;for(let y=Math.floor((b.y+epsilon)/16);y<=Math.floor((b.bottom-epsilon)/16);y++)for(let x=Math.floor((b.x+epsilon)/16);x<=Math.floor((b.right-epsilon)/16);x++)if(scene.collisionCells.has(y*scene.map.width+x))return true;return false;}
function stop(){scene.player.body.setVelocity(0,0);scene.greg.setFrame(scene.facing*3+1);}
function walkTo(x,y,label){phase=label;show(label);return new Promise((resolve,reject)=>{motion={kind:'target',x,y,resolve,reject,started:performance.now()};});}
function push(direction,ms,label){phase=label;show(label);return new Promise((resolve,reject)=>{motion={kind:'push',direction,until:performance.now()+ms,resolve,reject,started:performance.now()};});}
async function save(name,kind,value){const response=await fetch('/qa/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,[kind]:value})});if(!response.ok)throw Error('Save '+name+': '+response.status);return response.json();}
async function capture(name){await rendered();await save(name+'-native-1x','png',game.canvas.toDataURL('image/png'));const s=snapshot();report.checkpoints.push({name,...s});await save(name+'-state','report',s);}
function record(name){const stream=game.canvas.captureStream(30),chunks=[];const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:2500000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start();return async()=>{await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop();});stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'video/webm'});const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob);});await save(name,'webm',data);return {bytes:blob.size,type:blob.type};};}
async function traverse(leg){for(const p of leg.points)await walkTo(p.x,p.y,leg.goal.name);if(leg.goal.kind==='workbench-seat'){for(const p of leg.contactApproachSweep.points)await walkTo(p.x,p.y,'Checked seat approach: '+leg.goal.name);await push(leg.goal.pushDirection,450,'Physical contact: '+leg.goal.name);stop();const s=snapshot(),p=leg.goal.target;assert(leg.goal.id+' exact table contact',Math.abs(s.player.x-p.x)<.001&&Math.abs(s.player.y-p.y)<.001,{expected:p,actual:s.player});assert(leg.goal.id+' source body',Math.abs(s.body.x-(p.x-8))<.001&&Math.abs(s.body.y-p.y)<.001&&s.body.width===16&&s.body.height===16&&s.body.immovable,s.body);}else {assert(leg.goal.id+' reached',Math.abs(scene.player.x-leg.goal.target.x)<.001&&Math.abs(scene.player.y-leg.goal.target.y)<.001,snapshot().player);if(leg.goal.facing){scene.facing={south:0,west:1,east:2,north:3}[leg.goal.facing];stop();}}}
async function runProof(mode){if(running)return;running=true;document.querySelector('#verify').disabled=true;document.querySelector('#short').disabled=true;report=freshReport(mode);let finish;
try{const plan=scene.routePlan;assert('compiled route plan',plan.status==='pass',plan.failures);assert('Phaser 3.86',Phaser.VERSION==='3.86.0',Phaser.VERSION);assert('native 1x canvas',game.canvas.width===1024&&game.canvas.height===704&&scene.cameras.main.zoom===1,snapshot().renderer);assert('finite 16px TMJ',scene.map.tileWidth===16&&scene.map.tileHeight===16&&scene.map.width===156&&scene.map.height===88,{tileWidth:scene.map.tileWidth,width:scene.map.width,height:scene.map.height});assert('untouched source spawn',Math.abs(scene.player.x-plan.spawn.x)<.001&&Math.abs(scene.player.y-plan.spawn.y)<.001,snapshot().player);
const legs=mode==='short-desk-walk'?plan.legs.slice(0,4):plan.legs;
if(mode==='short-desk-walk'){const first=legs[0];for(const p of first.points)await walkTo(p.x,p.y,'Walk to Operations');finish=record('short-native-desk-walk');first.points=[first.points[first.points.length-1]];}
for(let i=0;i<legs.length;i++){await traverse(legs[i]);const goal=legs[i].goal;if(i===0||i%4===3||goal.kind==='shared-space')await capture(mode+'-'+goal.id);if(mode==='short-desk-walk')await pause(300);}
if(finish){report.video=await finish();finish=null;}assert('no solid-tile overlap',report.samples.every(s=>!s.overlap),{samples:report.samples.length});assert('native Woka throughout',report.samples.every(s=>s.spriteWidth===32&&s.spriteHeight===32&&s.scaleX===1&&s.scaleY===1&&s.bodyWidth===16&&s.bodyHeight===16&&s.immovable),{samples:report.samples.length});assert('fixed 1x camera throughout',report.samples.every(s=>s.zoom===1),{samples:report.samples.length});assert('no runtime errors',report.errors.length===0,report.errors);report.compile=scene.compile;report.completed=true;report.finishedAt=new Date().toISOString();report.testedLegs=legs.map(l=>l.goal.id);await save(mode+'-verification','report',report);show('PASS: '+legs.length+' continuous destinations; native body and exact tile contacts.');
}catch(error){report.errors.push(String(error));if(motion){motion=null;stop();}if(finish)try{report.video=await finish();}catch(e){report.errors.push(String(e));}await save(mode+'-verification','report',report);show('FAIL: '+error.message);}finally{running=false;document.querySelector('#state').textContent=JSON.stringify({completed:report.completed,assertions:report.assertions,errors:report.errors,final:snapshot()},null,2);}}
class NativeOfficeScene extends Phaser.Scene{
preload(){this.load.json('map-data','../compiled-work/studenthub-expanded-office.tmj');this.load.tilemapTiledJSON('office','../compiled-work/studenthub-expanded-office.tmj');this.load.json('geometry','../compiled-work/runtime-geometry.json');this.load.json('route-plan','../compiled-work/route-plan.json');this.load.json('compile','../compiled-work/compile-manifest.json');this.load.json('collision-grid','../compiled-work/collision-grid.json');this.load.spritesheet('greg','assets/greg.png',{frameWidth:32,frameHeight:32});for(const name of ['floor','environment','rugs','objects','foreground','glass','overhead-shade','labels'])this.load.image('office-'+name,'../compiled-work/office-'+name+'-atlas.png');this.load.image('exact-collision','../compiled-work/collision-cell.png');}
create(){scene=this;this.geometry=this.cache.json.get('geometry');this.routePlan=this.cache.json.get('route-plan');this.compile=this.cache.json.get('compile');this.collisionCells=new Set(this.cache.json.get('collision-grid').blockedIndices);this.map=this.make.tilemap({key:'office'});this.cameras.main.setBackgroundColor('#0c2029').setZoom(1).setRoundPixels(true).setBounds(0,0,2496,1408);this.physics.world.setBounds(0,0,2496,1408);const terrains=this.map.tilesets.map(ts=>this.map.addTilesetImage(ts.name,ts.name));this.phaserLayers=[];this.gameMap={flatLayers:this.cache.json.get('map-data').layers};fork.buildLayers.call(this,this.map,terrains);this.collisionLayer=this.phaserLayers.find(l=>l.layer.name==='collision-permanent');this.collisionLayer.setCollisionByProperty({collides:true});
this.player=this.add.container(this.geometry.spawn.x,this.geometry.spawn.y);this.greg=this.add.sprite(0,0,'greg',10);this.player.add(this.greg);this.player.getBody=()=>this.player.body;fork.configureBody.call(this.player);this.facing=3;this.cameras.main.startFollow(this.player,true,1,1);this.physics.add.collider(this.player,this.collisionLayer,(_,tile)=>{if(report.collisions.length<1500)report.collisions.push({tileX:tile.x,tileY:tile.y,bodyX:this.player.body.x,bodyY:this.player.body.y,phase});});this.keys=this.input.keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT');document.querySelector('#verify').disabled=false;document.querySelector('#short').disabled=false;document.querySelector('#capture').disabled=false;document.querySelector('#verify').onclick=()=>runProof('continuous-office-route');document.querySelector('#short').onclick=()=>runProof('short-desk-walk');document.querySelector('#capture').onclick=()=>capture('manual-current');window.officeQA={snapshot,report:()=>report,runProof,capture};show('Ready. '+this.compile.status);}
update(time){if(!this.player)return;const p=this.player,b=p.body;let vx=0,vy=0;if(motion){if(document.visibilityState!=='visible'){const m=motion;motion=null;stop();m.reject(Error('QA tab lost foreground'));return;}if(performance.now()-motion.started>45000){const m=motion;motion=null;stop();m.reject(Error('Movement timed out: '+phase));return;}if(motion.kind==='push'){if(performance.now()>=motion.until){const m=motion;motion=null;stop();m.resolve();}else vy=motion.direction*settings.speed;}else{const dx=motion.x-(b.x+8),dy=motion.y-b.y;if(Math.abs(dx)<.001&&Math.abs(dy)<.001){const m=motion;motion=null;stop();m.resolve();}else if(Math.abs(dx)>.001)vx=Math.sign(dx)*Math.min(settings.speed,Math.abs(dx)/settings.dt);else vy=Math.sign(dy)*Math.min(settings.speed,Math.abs(dy)/settings.dt);}}else if(!running){vx=(this.keys.RIGHT.isDown||this.keys.D.isDown?1:0)-(this.keys.LEFT.isDown||this.keys.A.isDown?1:0);vy=(this.keys.DOWN.isDown||this.keys.S.isDown?1:0)-(this.keys.UP.isDown||this.keys.W.isDown?1:0);if(vx&&vy){vx/=Math.SQRT2;vy/=Math.SQRT2;}vx*=settings.speed;vy*=settings.speed;}
b.setVelocity(vx,vy);if(vy<0)this.facing=3;else if(vy>0)this.facing=0;else if(vx<0)this.facing=1;else if(vx>0)this.facing=2;const moving=Math.hypot(b.deltaX(),b.deltaY())>.01;this.greg.setFrame(this.facing*3+(moving?Math.floor(time/130)%3:1));p.setDepth(fork.characterDepth.call(p));if(running&&time-lastSample>=30){lastSample=time;report.samples.push({time,phase,x:b.x+8,y:b.y,overlap:bodyOverlap(),bodyWidth:b.width,bodyHeight:b.height,immovable:b.immovable,spriteWidth:this.greg.width,spriteHeight:this.greg.height,scaleX:this.greg.scaleX,scaleY:this.greg.scaleY,zoom:this.cameras.main.zoom});}if(!running&&time-lastSample>300){lastSample=time;document.querySelector('#state').textContent=JSON.stringify(snapshot(),null,2);}}
}
game=new Phaser.Game({type:Phaser.CANVAS,parent:'game',width:1024,height:704,backgroundColor:'#0c2029',pixelArt:true,antialias:false,roundPixels:true,physics:{default:'arcade',arcade:{gravity:{x:0,y:0},fps:60,fixedStep:true,debug:false}},scene:NativeOfficeScene});
