import fs from'node:fs';import assert from'node:assert/strict';
const N=new URL('../',import.meta.url),g=JSON.parse(fs.readFileSync(new URL('native-manifest.json',N)));const size=8,w=128,h=128;
function poly(p,ps){let c=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++){const a=ps[i],b=ps[j];if((a[1]>p.y)!==(b[1]>p.y)&&p.x<(b[0]-a[0])*(p.y-a[1])/(b[1]-a[1])+a[0])c=!c;}return c;}
const solid=p=>!g.walkable.some(polygon=>poly(p,polygon))||g.obstacles.some(o=>o.type==='circle'?Math.hypot(p.x-o.x,p.y-o.y)<=o.radius:p.x>=o.x&&p.x<o.x+o.width&&p.y>=o.y&&p.y<o.y+o.height);
const grid=[];for(let ty=0;ty<h;ty++)for(let tx=0;tx<w;tx++){let blocked=0;for(let y=0;y<size&&!blocked;y++)for(let x=0;x<size;x++)if(solid({x:tx*size+x+.5,y:ty*size+y+.5})){blocked=1;break;}grid.push(blocked);}
function clear(p){const left=p.x-8,right=p.x+8-.0001,top=p.y,bottom=p.y+16-.0001;if(left<0||right>=1024||top<0||bottom>=1024)return false;for(let y=Math.floor(top/8);y<=Math.floor(bottom/8);y++)for(let x=Math.floor(left/8);x<=Math.floor(right/8);x++)if(grid[y*w+x])return false;return true;}
function sweep(a,b){const n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)));for(let i=0;i<=n;i++)if(!clear({x:a.x+(b.x-a.x)*i/n,y:a.y+(b.y-a.y)*i/n}))return false;return true;}
function route(a,b){if(!clear(a)||!clear(b))return null;const key=p=>p.x+','+p.y,q=[a],prev=new Map([[key(a),null]]);for(let i=0;i<q.length;i++){const p=q[i];if(key(p)===key(b)){const path=[];let t=p;while(t){path.push(t);t=prev.get(key(t));}return path.reverse();}for(const [dx,dy]of[[8,0],[-8,0],[0,8],[0,-8]]){const t={x:p.x+dx,y:p.y+dy},k=key(t);if(!prev.has(k)&&sweep(p,t)){prev.set(k,p);q.push(t);}}}return null;}
const results=g.spots.map(s=>{const path=route(g.entry,s.position),approach=route(g.entry,s.approach);return{id:s.id,position:s.position,approach:s.approach,entryToPosition:Boolean(path),approachReachable:Boolean(approach),approachToPosition:sweep(s.approach,s.position),reverseExit:sweep(s.position,s.approach),bodyFitsPermanentGrid:clear(s.position),waypoints:path??[]};});
const merged=[];const active=new Map();for(let y=0;y<h;y++){const row=[];for(let x=0;x<w;){if(!grid[y*w+x]){x++;continue;}const start=x;while(x<w&&grid[y*w+x])x++;row.push([start,x]);}const next=new Map();for(const [a,b]of row){const k=a+','+b,old=active.get(k);if(old){old.height+=8;next.set(k,old);}else{const r={x:a*8,y:y*8,width:(b-a)*8,height:8};merged.push(r);next.set(k,r);}}active.clear();for(const[k,v]of next)active.set(k,v);}
const out={passed:results.every(r=>r.entryToPosition&&r.approachReachable&&r.approachToPosition&&r.reverseExit),scope:'permanent 8px physical grid, continuous16×16 body, no bench mode or state',worldOrigin:g.worldOrigin,tileSize:8,gridWidth:128,gridHeight:128,blockedCellCount:grid.filter(Boolean).length,results};fs.writeFileSync(new URL('docs/permanent-grid-verification.json',N),JSON.stringify(out,null,2)+'\n');fs.writeFileSync(new URL('collision-grid-8px.json',N),JSON.stringify({width:w,height:h,tileSize:8,avatar:g.avatar,worldOrigin:g.worldOrigin,blocked:grid})+'\n');fs.writeFileSync(new URL('collision-rectangles.json',N),JSON.stringify({worldOrigin:g.worldOrigin,units:'native pixels; add origin for host world coordinates',rectangles:merged},null,2)+'\n');console.log(JSON.stringify({...out,results:results.map(({waypoints,...r})=>({...r,waypointCount:waypoints.length}))},null,2));
